<?php

return [
    'avatar' => 'avatar',
    'background' => 'background',
    'folderUpload' => 'uploads/',
    'pathUpload' => '/uploads/',
    'userAvatarDefault' => '/templates/admin/images/avatar_user_default.png',
    'userBackgroundDefault' => '/templates/admin/images/background_user_default.jpg',
    'paginate' => 10,
    'default_parent_id' => 0,
    'lessonPictureDefault' => '/templates/admin/images/lesson_picture_default.png',
    'picture' => 'picture',
    'number_course' => 4,
    'status_follow_default' => 1,
    'status_follow_block' => 0,
    'learnIcon' => '/templates/elearning/images/learned-icon.png',
    'unlearnIcon' => '/templates/elearning/images/unlearn-icon.png',
    'checkIcon' => '/templates/elearning/images/check-icon.png',
    'leaderIcon' => '/templates/elearning/images/Leaderboard_Icon.png',
    'rank0' => '/templates/elearning/images/rankIcon/0.png',
    'rank1' => '/templates/elearning/images/rankIcon/1.png',
    'rank2' => '/templates/elearning/images/rankIcon/2.png',
    'rank3' => '/templates/elearning/images/rankIcon/3.png',
    'rank4' => '/templates/elearning/images/rankIcon/4.png',
    'rank5' => '/templates/elearning/images/rankIcon/5.png',
    'rank6' => '/templates/elearning/images/rankIcon/6.png',
    'rank7' => '/templates/elearning/images/rankIcon/7.png',
    'rank8' => '/templates/elearning/images/rankIcon/7.png',
    'rank9' => '/templates/elearning/images/rankIcon/7.png',
    'rank10' => '/templates/elearning/images/rankIcon/7.png',
    'topUser' => 10,
    'progressValDefault' => 0,
    'percent' => 100,
    'filterSelectAllLessons' => 0,
    'filterAllWord' => 1,
    'filterAlphabet' => 2,
    'filterLearned' => 3,
    'filterUnlearn' => 4,
];
